apps/lobby/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from apps.lobby.views import GameList, GameCreate, GameWaiting, GameDelete, save_session

app_name = 'lobby'

urlpatterns = [
    url('^$', GameList.as_view(), name='index'),
    url('save_session/', save_session, name='save_session'),
    url('game_create/', GameCreate.as_view(), name='game_create'),
    url('game_waiting/(?P<game_id>[0-9]+)/', GameWaiting.as_view(), name='game_waiting'),
    url('game_delete/(?P<pk>[0-9]+)/', GameDelete.as_view(), name='game_delete'),
]

carcassonne/urls.py
# -*- coding: utf-8 -*-

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.lobby.urls'),),
    path('game/', include('apps.game.urls')),
]

templates/base/base.html
{# Load the tag library #}
{% load staticfiles %}
{% load bootstrap4 %}
{% bootstrap_css %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Carcassonne</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% block head %}
    {% endblock %}

</head>
<body bgcolor="black">

    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top d-flex">
        <a class="navbar-brand" href="{% url 'lobby:index' %}">Carcassonne</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if request.get_full_path == '/' %}
            <div class="ml-auto">
                {% if 'player_name' in request.session %}
                     <a href="{% url 'lobby:save_session' %}">
                        <button type="button" class="btn btn-outline-success" title="Borrar el nombre de la session">
	                        Borrar nombre
                        </button>
                    </a>
                    <a href="{% url 'lobby:game_create' %}">
                        <button type="button" class="btn btn-outline-info">Crear partida</button>
                    </a>
                {% else %}
                   <button type="button" class="btn btn-outline-success" data-toggle="modal" data-target="#modalName">
	                    Nombre
                    </button>
                {% endif %}
            {% endif %}
            </div>
        </div>
    </nav>
    <br><br><br>
    {% endblock %}

    {% block content %}
    {% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="{% static 'js/DjangoAjax.js' %}"></script>

    {% block ajax %}
    {% endblock %}

    {% block extrajs %}
    {% endblock %}
</body>
</html>