apps/game/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import (
    init_game, get_score, get_piece, get_turn, get_amount_pieces,
    set_piece, set_piece_rotation, get_amount_followers,
    set_follower_to_piece, get_follower, step, update_pieces
)

app_name = 'game'

urlpatterns = [
    url('init_game/(?P<game_id>[0-9]+)/', init_game, name='init_game'),
    url('ajax/get_score/(?P<game_id>[0-9]+)/', get_score, name='get_score'),
    url('ajax/get_piece/(?P<game_id>[0-9]+)/', get_piece, name='get_piece'),
    url('ajax/get_turn/(?P<game_id>[0-9]+)/', get_turn, name='get_turn'),
    url('ajax/get_amount_pieces/(?P<game_id>[0-9]+)/', get_amount_pieces, name='get_amount_pieces'),
    url('ajax/set_piece/(?P<game_id>[0-9]+)/', set_piece, name='set_piece'),
    url('ajax/set_piece_rotation/(?P<game_id>[0-9]+)/', set_piece_rotation, name='set_piece_rotation'),
    url('ajax/get_amount_followers/(?P<game_id>[0-9]+)/', get_amount_followers, name='get_amount_followers'),
    url('ajax/get_follower/(?P<game_id>[0-9]+)/', get_follower, name='get_follower'),
    url('ajax/set_follower_to_piece/(?P<game_id>[0-9]+)/', set_follower_to_piece, name='set_follower_to_piece'),
    url('ajax/step/(?P<game_id>[0-9]+)/', step, name='step'),
    url('ajax/update_pieces/(?P<game_id>[0-9]+)/', update_pieces, name='update_pieces'),
]

apps/lobby/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from apps.lobby.views import GameList, GameCreate, GameWaiting, GameDelete, save_session

app_name = 'lobby'

urlpatterns = [
    url('^$', GameList.as_view(), name='index'),
    url('save_session/', save_session, name='save_session'),
    url('game_create/', GameCreate.as_view(), name='game_create'),
    url('game_waiting/(?P<game_id>[0-9]+)/', GameWaiting.as_view(), name='game_waiting'),
    url('game_delete/(?P<pk>[0-9]+)/', GameDelete.as_view(), name='game_delete'),
]

carcassonne/urls.py
# -*- coding: utf-8 -*-

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.lobby.urls'),),
    path('game/', include('apps.game.urls')),
]

apps/lobby/models.py
# -*- coding: utf-8 -*-

from django.db import models as md


class Game(md.Model):
    """ class with the data of the game """
    STATUS = [('waiting', 'Waiting'),
              ('started', 'Started'),
              ('finished', 'Finished')]
    BOTS = ((0, 0), (1, 1), (2, 2), (3, 3))
    name = md.CharField(max_length=20, unique=True)
    status = md.CharField(max_length=20, default='waiting', choices=STATUS)
    turn = md.IntegerField(default=-1)
    bots = md.IntegerField(default=0, choices=BOTS)

    def __str__(self):
        return '{} ({})'.format(self.name, self.status)

    def is_turn_of(self, player_name):
        player = Player.objects.get(id=self.turn)
        return player_name == player.name

    def change_turno(self):
        players = Player.objects.filter(game=self).order_by('id')
        new_player = None
        for p in players:
            if p.id > self.turn:
                new_player = p
                break
        if not new_player:
            new_player = players.first()
        self.turn = new_player.id
        self.save()

    class Meta:
        ordering = ('name', 'status')


class Player(md.Model):
    name = md.CharField(max_length=20, unique=True)
    points = md.IntegerField(default=0)
    game = md.ForeignKey(Game, null=True, blank=True, on_delete=md.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

apps/lobby/forms.py
# -*- coding: utf-8 -*-

from django import forms as fm

from .models import Game, Player


class GameForm(fm.ModelForm):

    class Meta:
        model = Game

        fields = ['name', 'bots']
        labels = {
            'name': 'Nombre',
            'bots': 'Bots',
        }
        widgets = {
            'name': fm.TextInput(attrs={'class': 'form-control form-inline'}),
            'bots': fm.Select(attrs={'class': 'form-control form-inline'})
        }


class PlayerForm(fm.ModelForm):

    class Meta:
        model = Player

        fields = '__all__'

apps/lobby/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.db.models import Count, Q
from django.views.generic import ListView, CreateView, TemplateView, DeleteView
from django.urls import reverse_lazy, reverse

from .models import Game, Player
from .forms import GameForm, PlayerForm


def save_session(request):
    if request.method == 'GET':
        try:
            Player.objects.get(name=request.session['player_name']).delete()
            del request.session['player_name']
        except KeyError:
            pass
    else:
        player_name = request.POST['player_name']
        request.session['player_name'] = player_name
        if Player.objects.filter(name=player_name).exists():
            context = {'conflic_name': True}
            return render(request, 'lobby/game_list.html', context=context)
        playerfm = PlayerForm({'name': player_name, 'points': 0})
        if playerfm.is_valid():
            playerfm.save()
    return render(request, 'lobby/game_list.html')


class GameList(ListView):
    model = Game
    template_name = 'lobby/game_list.html'
    form_class = GameForm


class GameCreate(CreateView):
    model = Game
    form_class = GameForm
    template_name = 'lobby/game_create.html'

    def get_success_url(self):
        return reverse('lobby:game_waiting', args=(self.object.id,))


class GameWaiting(TemplateView):
    model = Game
    template_name = 'lobby/game_waiting.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        players_in_game = Player.objects.filter(game_id=kwargs['game_id'])
        context['players_name'] = players_in_game
        context['game'] = Game.objects.get(id=kwargs['game_id'])
        if 'creador' in kwargs:
            context['creador'] = True
        return context

    def get(self, request, *args, **kwargs):
        player_name = request.session['player_name']
        player = Player.objects.get(name=player_name)
        game = Game.objects.get(id=kwargs['game_id'])
        player.game = game
        player.save()
        return super().get(request, *args, **kwargs)


class GameDelete(DeleteView):
    pass
#     model = Game
#     template_name = 'lobby/game_list.html'
#     success_url = reverse_lazy('lobby:index')

templates/lobby/game_create.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}


{% block content %}
<div align="center" >
    <form method="post">
        {% csrf_token %}
         <div align="left" class="col-auto">
            {{ form.as_p }}
          </div>
        <button type="submit">Guardar</button>
    </form>
</div>
{% endblock %}

templates/lobby/game_list.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}

{% block ajax %}
    {% if 'player_name' not in request.session %}
        {% if conflic_name %}
            <script type="text/javascript">
                function (data) {
                    $("#conficName").show();
                    alert('Nombre ya usado');
                }
            </script>
        {% endif %}
        <script type="text/javascript">
              $(document).ready(function() {
                 $("#modalName").modal("show");
              });
        </script>
    {% endif %}
   
{% endblock %}


{% block content %}
    <div class="modal fade" id="modalName" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header" align="center">
                    <h4 align="center" class="modal-title" id="myModalLabel">Nombre</h4>
                </div>
                <div class="modal-body" align="center">
                    <form action="{% url 'lobby:save_session' %}" method="post">
                     {% csrf_token %}
                        <input id="playerName" class="form-control required" type="text" name="player_name">
                        <button type="submit" class="btn btn-outline-success">OK</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="conficName" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header" align="center">
                    <h4 align="center" class="modal-title" id="myModalLabel">Nombre ya en uso</h4>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="welcome" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header" align="center">
                    <h4 align="center" class="modal-title" id="myModalLabel">Bienvenido {{ request.session.player_name }}</h4>
                </div>
            </div>
        </div>
    </div>
    <br><br>
     <div class="container">
                <div align="center">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <td>#</td>
                                <td>Jugador</td>
                            </tr>
                        </thead>
                        <tbody>
                            {% if object_list %}
                            {% for game in object_list %}
                            <tr>
                                <td>{{ game.id }}</td>
                                <td>{{ game.name }}</td>
                                <td>
                                    <a class="btn btn-primary" href="{% url 'lobby:game_waiting' game.id %}">Unirse</a>
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                                <h1>No hay partidas en espera</h1>
                            {% endif %}
                        </tbody>
                    </table>

                </div>
     </div>
{% endblock %}

templates/lobby/game_waiting.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}


{% block content %}
     <div class="container">
        {% if players_name %}
        {% for player in players_name %}
            <label type="text">->{{ player.name }}</label>
        {% endfor %}
        {% else %}
            <h2 align="center">Esperando usuarios</h2><br>
        {% endif %}
    </div>
    <div class="container">
        <a href="{% url 'game:init_game' game.id %}">
            <button>Iniciar</button>
        </a>
    </div>
{% endblock %}